# Pytorch for beginers

This booklet aims to show the first steps to follow when creating a model with pytorch and its main features.

In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

1.13.0+cu116


# 🟦EN Introducton to Tensors

# 🟥ES Introducción a los tensores.

### Creating tensors

In [3]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

To see more information of  [Pytotch tensors](https://pytorch.org/docs/stable/tensors.html)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor as Python int
scalar.item()

7

In [6]:
# Vector
vec = torch.tensor([7,7])
vec

tensor([7, 7])

In [7]:
vec.ndim

1

In [8]:
vec.shape

torch.Size([2])

In [9]:
# Matrix

matrix = torch.tensor([[1,1],
                       [2,1]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[1]

tensor([2, 1])

In [13]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                        [3,5,7],
                        [1,2,3]]])

tensor

tensor([[[1, 2, 3],
         [3, 5, 7],
         [1, 2, 3]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

***🟦EN*** The first number (x) of torch.Size([x, y, z]) means the number of dimensions of the matrix, the second number (y), represents the number of vectors that compose the matrix, and the last number (z) means reflects the number of numbers that are in the matrix per neighbor, and the last number (z) means the number of vectors that compose the matrix.

***🟥ES*** El primer numero(x) de torch.Size([x, y, z]) significa el numero de dimensiones de la matriz, en segundo numero (y), representa el número de vectores que componen la matriz, y el ultimo número (z) significa refleja la cantidad de números que hay por vec

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [3, 5, 7],
        [1, 2, 3]])

In [17]:
tensor[0][0]

tensor([1, 2, 3])

In [18]:
tensor[0][0][0]

tensor(1)

## Random tensors

***🟦EN***:The random tensors are important becuase the way many neuronal networks learn is that they start with ramdom number in their tensors and adjus those to better represent the data. 


***🟥ES***:Los tensores aleatorios son importantes porque la forma en que muchas redes neuronales aprenden es que empiezan con números aleatorios en sus tensores y los ajustan para representar mejor los datos. 

In [19]:
# Create random tensor of size [3, 4]
rand_tensor = torch.rand(3, 4)
rand_tensor

tensor([[0.9596, 0.5139, 0.1665, 0.7326],
        [0.5657, 0.1587, 0.8822, 0.8060],
        [0.2326, 0.1880, 0.4251, 0.1442]])

In [20]:
rand_tensor2 = torch.rand(7, 2, 2)
rand_tensor2

tensor([[[0.7002, 0.2449],
         [0.8617, 0.3752]],

        [[0.4581, 0.5743],
         [0.3736, 0.7038]],

        [[0.3468, 0.3813],
         [0.3304, 0.2847]],

        [[0.1095, 0.9110],
         [0.5412, 0.5250]],

        [[0.9848, 0.1429],
         [0.2374, 0.6673]],

        [[0.1807, 0.9379],
         [0.9907, 0.0670]],

        [[0.5067, 0.5470],
         [0.0397, 0.7777]]])

In [21]:
# Create random tensor with similar shapo to an imgae
HEIGHT = 224
WIDTH = 224
COLOR = 3 # Black and with = 1
rand_img_tensor = torch.rand(size=(HEIGHT, WIDTH, COLOR)) # height, width, RGB (in this case)
print(f"Shape: {rand_img_tensor.shape}\nNDIM: {rand_img_tensor.ndim}\nDType: {rand_img_tensor.dtype}")

Shape: torch.Size([224, 224, 3])
NDIM: 3
DType: torch.float32


In [22]:
# Tensor all zeros
zero_tensor = torch.zeros(size=(3, 4))
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Tensor all one
one_tensor = torch.ones(size=(4,4))
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Create a range of tensors and tensors-like

In [24]:
arange_ = torch.arange(0, 10)
# To 1 - 10:
one_ten = torch.arange(1, 11)
one_ten

print(f"arange(0,10): {arange_}\n arange(1, 11): {one_ten}")

arange(0,10): tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 arange(1, 11): tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [25]:
step = torch.arange(start=0, end=3000, step=94)
step

tensor([   0,   94,  188,  282,  376,  470,  564,  658,  752,  846,  940, 1034,
        1128, 1222, 1316, 1410, 1504, 1598, 1692, 1786, 1880, 1974, 2068, 2162,
        2256, 2350, 2444, 2538, 2632, 2726, 2820, 2914])

In [26]:
# tensor-like (Transform all the numbers to 0)
ten_zeros = torch.zeros_like(input=one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

***🟦EN***: Datatypes is a common error in DeepLearnig con PyTorch

***🟥ES***: Los Datatypes son un error comun en DeepLearnign con PyTorch

***🟦EN***: The principal error in are:
1. Tensor no rigth datatype.
2. Tensor not right shape.
3. Tensor not right device.

***🟥ES***: Los principales errores són:
1. Tensors sin el datatype correcto
2. Tensor no tiene la forma correcta
3. Tensor sin el dispositivo correcto.

In [27]:
# float32 tensor

f_32_tensor = torch.tensor([3.0, 5.0, 6.0], dtype=None,
                           device=None,
                           requires_grad=False) 
f_32_tensor
# If dtype is not specificated the default dtype is float32

tensor([3., 5., 6.])

In [28]:
tensor_correct = torch.tensor([3.0, 2.0, 1.0],
                              dtype=None,
                              device="cpu", # cuda with gpu
                              requires_grad=False)
tensor_correct

tensor([3., 2., 1.])

In [29]:
print(f"DataType: {tensor_correct.dtype}")

DataType: torch.float32


### Get information from tensors
1. Tensor no rigth datatype -- To do get datatype from tensor, can use ```tensor.dtype```
2. Tensor not right shape -- To get shape from a tensor, can use `tensor.shape`
3. Tensor not right device -- To get devide from a tensor, can use `tensor.device`

In [30]:
ex_tensor = torch.rand(4,4)
ex_tensor

tensor([[0.2135, 0.6608, 0.0049, 0.7020],
        [0.7424, 0.3754, 0.5969, 0.4515],
        [0.6646, 0.5094, 0.2655, 0.1678],
        [0.8807, 0.5433, 0.1999, 0.3255]])

In [31]:
# Get details form a tensor
print(f"{ex_tensor}\nDataType: {ex_tensor.dtype}\nShapeTensor: {ex_tensor.shape}\nDevice: {ex_tensor.device}")

tensor([[0.2135, 0.6608, 0.0049, 0.7020],
        [0.7424, 0.3754, 0.5969, 0.4515],
        [0.6646, 0.5094, 0.2655, 0.1678],
        [0.8807, 0.5433, 0.1999, 0.3255]])
DataType: torch.float32
ShapeTensor: torch.Size([4, 4])
Device: cpu


### Editic tensors

Tensor operation include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [32]:
ten = torch.tensor([12, 2, 5])

In [33]:
# Create a tensor
%%time
print(f"Default tensor: {ten}\nTensor adding 10: {ten + 10}\nTensor muliply per 10: {ten * 10}\nSubstract 10: {ten - 10}")

Default tensor: tensor([12,  2,  5])
Tensor adding 10: tensor([22, 12, 15])
Tensor muliply per 10: tensor([120,  20,  50])
Substract 10: tensor([ 2, -8, -5])
CPU times: user 4.99 ms, sys: 0 ns, total: 4.99 ms
Wall time: 14 ms


In [34]:
# Using PyTorch funtions to do the same
%%time
print(f"Default tensor: {ten}\nTensor adding 10: {torch.add(ten, 10)}\nTensor muliply per 10: {torch.mul(ten, 10)}\nSubstract 10: {torch.sub(ten, 10)}")

Default tensor: tensor([12,  2,  5])
Tensor adding 10: tensor([22, 12, 15])
Tensor muliply per 10: tensor([120,  20,  50])
Substract 10: tensor([ 2, -8, -5])
CPU times: user 1.31 ms, sys: 0 ns, total: 1.31 ms
Wall time: 1.34 ms


### Matrix multiplication

Two main ways of performing multiplications in NN (Neuronal networks) & DL (Deep learning):

1. Matrix multiplication (IMPORTANT)
2. Element-wise multiplication

In [35]:
# Element wise multiplication

print(f"{ten} * {ten} = {ten * ten}\n#################\nPytorch funcion: {torch.matmul(ten, ten)}")

tensor([12,  2,  5]) * tensor([12,  2,  5]) = tensor([144,   4,  25])
#################
Pytorch funcion: 173


***🟦EN***: Let's see the time dif usign matmul and to do it by hand

***🟥ES***: Vamos a ver la diferencia aciendolo usando matmaul o haciendolo a mano.

In [36]:
# Matrix mult by hand
%%time
val = 0
for i in range(len(ten)):
  val += ten[i] * ten[i]
print(val)

tensor(173)
CPU times: user 2.8 ms, sys: 213 µs, total: 3.01 ms
Wall time: 9.23 ms


In [37]:
%%time
torch.matmul(ten, ten) # is the same as torch.mm(x, x)

CPU times: user 82 µs, sys: 0 ns, total: 82 µs
Wall time: 86.5 µs


tensor(173)

Two main rules that performing matrix multiplication needs to satisfy:
1. The *inner dimensions* must match:
* `(3, 2) @ (3, 2)` Must work
* `(7, 3) @ (3, 7)` Works
* `(4, 2) @ (2, 4)` Works
The resutl matrix has teh shape of the *outer dimension*
* `(2, 3) @ (3, 2)` ==> `(2, 2)`
* `(7, 3) @ (3, 7)` ==> `(7, 7)`

In [38]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.2869, 0.1848, 0.3731],
        [0.0600, 0.0509, 0.1040],
        [0.2447, 0.2262, 0.4635]])

In [39]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

### Common error in deep learnin => Shape errors

In [40]:
# Shape for matrix => See the proccess http://matrixmultiplication.xyz/
tensor1 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor2 = torch.tensor([[7, 8],
                        [9, 5],
                        [3, 2]])


***🟦EN***: In this case we can't multiply `tensor1` per `tensor2`, to manipulte the shape of on eof our tensors using a **transpose**, this funciton, switches the dimension of a given tensor.

***🟥ES***: Es este caso, no podemos multiplicat el `tensor1` por el `tensor2`, para manipualr la dimension de uno de los tensores usaremos la funcion **transpose**, esta dimensión intercambia la dimensión del tensor dado.

In [41]:
print(f"Default tensor: {tensor1}\nTrasosed tensor: {tensor1.T}\nShape of default tensor {tensor1.shape}\nTransposed shape: {tensor1.T.shape}")

Default tensor: tensor([[1, 2],
        [3, 4],
        [5, 6]])
Trasosed tensor: tensor([[1, 3, 5],
        [2, 4, 6]])
Shape of default tensor torch.Size([3, 2])
Transposed shape: torch.Size([2, 3])


In [42]:
# Now can multiplication works when the tensor2 is transposed

torch.mm(tensor1, tensor2.T)

tensor([[23, 19,  7],
        [53, 47, 17],
        [83, 75, 27]])

## Find th max, min, mean, sum...(tensor aggregation)


In [43]:
# Tensor creation

tensor = torch.arange(0, 100, 5)
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [44]:
print(f"Max: {torch.max(tensor)} // {tensor.max()}\nMin: {torch.min(tensor)} // {tensor.min()}")

# If we try to average this tensor, we will get an error due to an incorrect datatype.

tensor.dtype # https://pytorch.org/docs/stable/generated/torch.mean.html

Max: 95 // 95
Min: 0 // 0


torch.int64

In [45]:
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(47.5000), tensor(47.5000))

In [48]:
# Find the sum
torch.sum(tensor), tensor.sum()

(tensor(950), tensor(950))

In [50]:
print(f"ArgMin: {tensor.argmin()} ArgMax: {tensor.argmax()}")

ArgMin: 0 ArgMax: 19


## Reshaping, stackng, squeezing and unsequeezing tensors.

***🟦EN***: 
* **Reshaping**: Reshapes an input tensor to a defined shape.
* **View**: Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* **Stacking**: Combine multiple tensors on top of each other (vstack) or side by side. 

***🟥ES***:
* **Reshaping**: Da nueva forma a un tensor de entrada con una forma definida.
* **View**: Devuelve una vista de un tensor de entrada de cierta forma pero manteniendo la misma memoria que el tensor original.
* **Stacking**: Combina varios tensores uno encima de otro (vstack) o uno al lado del otro. 

***🟦EN***

***🟥ES***:

***🟦EN***

***🟥ES***:

***🟦EN***

***🟥ES***:

***🟦EN***

***🟥ES***:

***🟦EN***

***🟥ES***: